### PR TITLE
Add Kress Mission RTK support

### LINKED ISSUE #442: [FR]: Kress Mission RTKn Support
### Describe the feature you wish to make a request for

It seems like there is no support het for the Kress Mission RTK series but don't know for sure 

Could you specify models/series dat are supported? And maybe list them in the readme

Really looking forward to us HA with my Kress KR174E.

### Describe alternatives you've considered

None

### Additional context

.

### PR DESCRIPTION
**Pull request by MTrab**
Fixes #442

Functions and attributes may still be missing - when found, please create issues for this.

A big thanks to @cm86 for giving access to his mower

### CODE REVIEW

**Comment by cm86** [comment]
thanks for the nice work on your integration

**Comment by smornierHA** [comment]
Hello thanks for the integratin of mission RTK, unfortunately I’m not able to Connect my mower the l’android cloud the mission rtk serial number is not recognized so I dont understand how to Connect to HA integration.
Thank you in advanced for your help

**Comment by cm86** [comment]
You have to delete the old version completely. Also delete the entity wich was created by the old version.
Then restart HA and install the new version...
By creating the device with the new version you just have to insert your credentials and that's it...
Now you have a mower with the new "lawn_mower" entity...

Mit freundlichen Grüßen 
Chris

**Comment by smornierHA** [comment]
Thank you very much for your quick and relevant feedback, it works perfeclty now !!

**Pull request merged**
