### PR TITLE
Adding minutes and meters as attributes

### LINKED ISSUE #536: [FR]: Add entity for worktime in minutes
### Describe the feature you wish to make a request for

Currently `worktime_total` is the work time in hours. It's derived from the work time in minutes which is provided by pyworxcloud. The work time in HA should be provided in minutes instead (or at least additionally) since you can always derive the hours from the minutes but not vice-versa due to rounding.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MTrab**
Adding minutes as attribute to:
* Blades Total On Time
* Blades Current On Time
* Blades Reset At Hours
* Total Worktime

Adding meters as attribute to:
* Distance Driven

Fixes #536

### CODE REVIEW

**Comment by mbo18** [comment]
You may also have used the `duration` device class and the `distance` device class with a native unit of measurement. With that people would be able to change the unit directly in the frontend

**Comment by MTrab** [comment]
The information is added as attributes, not state. Så the units have not changed.
If users wish to use the data as seperate sensors, then they can create them using a template sensor.

**Comment by MTrab** [comment]
Also - the deviceclasses are already set to what you suggest

**Comment by mbo18** [comment]
> Also - the deviceclasses are already set to what you suggest

True but not for worktime total.

Attributes add data to the DB, data that is already here: Native unit of measurement can be set to what’s returned by the API (so meters and minutes here) and suggested unit of measurement set to km and hours. Then users would only have to change the unit in the frontend to get what they want (minutes, hours, days, etc). And the conversion is entirely managed by the backend. 
That is just an idea 🙂

**Comment by MTrab** [comment]
Interesting - didn't know that was a possibility.
I'll make some tests and see what that reveals.

**Comment by MTrab** [comment]
Okay - I tested this and it doesn't work. Not possible to change between minutes and hours in the settings for the sensors in Home Assistant.
So currently we'll stick with the minutes as an attribute.

**Pull request merged**
